site_name: Dashboard
site_description: An admin dashboard for use with ASGI web frameworks.

theme:
    name: 'material'

repo_name: encode/dashboard
repo_url: https://github.com/encode/dashboard
edit_uri: ""

nav:
    - Introduction: 'index.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - mkautodoc

extra_javascript:
  - 'js/chat.js'
  - 'js/sidecar-1.5.0.js'
