#!/bin/sh -e

if [ -d 'venv' ] ; then
    PREFIX="venv/bin/"
else
    PREFIX=""
fi

if [ ! -z "$GITHUB_ACTIONS" ]; then
  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
  git config --local user.name "GitHub Action"
fi

set -x

${PREFIX}pip install mkdocs mkdocs-material mkautodoc
${PREFIX}mkdocs gh-deploy --force
