#!/bin/sh -e

if [ -d 'venv' ] ; then
    PREFIX="venv/bin/"
else
    PREFIX=""
fi

echo GitHub Ref: $GITHUB_REF

set -x

${PREFIX}pip install twine
${PREFIX}pip install wheel
${PREFIX}python setup.py sdist bdist_wheel
${PREFIX}twine check
