#!/bin/sh -e

if [ -d 'venv' ] ; then
    PREFIX="venv/bin/"
else
    PREFIX=""
fi

VERSION=`grep __version__ ./dashboard/__init__.py | grep -o '[0-9][^"]*'`

set -x

${PREFIX}pip install twine
${PREFIX}pip install wheel
${PREFIX}python setup.py sdist bdist_wheel
if [ "refs/tags/${VERSION}" = "${GITHUB_REF}" ] ; then
  ${PREFIX}twine upload dist/*
else
  echo "GitHub Ref '${GITHUB_REF}' did not match package version '${VERSION}'"
  exit 1
fi
